<?php

namespace AdminBundle\Repository;

/**
 * PaintingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaintingRepository extends \Doctrine\ORM\EntityRepository
{
    const NB_ELEM_PAGE = 1;

    public function getPaintings ($page, $isCount = false) {

        $qb = $this->createQueryBuilder('p')
            ->where('p.isDisabled = 0')
            ->orderBy('p.createdAt', 'DESC')
        ;

        if ($isCount) {
            $qb->select('COUNT (p)');
            return $qb->getQuery()->getSingleScalarResult();
        }

        $query = $qb->getQuery();
        $query->setMaxResults(self::NB_ELEM_PAGE);
        $query->setFirstResult(($page -1 ) * self::NB_ELEM_PAGE);

        return $query->getResult();
    }
}
